### ISSUE TITLE
Publishing unicorn flavor for arm64 fails with template defaults

### ISSUE THREAD

**Issue by JeffResc** [uds-packages/template#30]
### Describe the issue
When using the template defaults set in the publish workflow and the root zarf.yaml, unicorn flavor builds for the arm64 architecture fail as the root zarf.yaml excludes arm64 architecture from unicorn builds, even though there is a workflow setup for it. Chainguard publishes arm64 images, so I believe removing the architecture requirement in the root zarf.yaml would be a sufficient resolution.

### Visual Proof (screenshots, videos, text, etc)
[Demonstration of the issue in the OpenSearch repo](https://github.com/defenseunicorns/uds-package-opensearch/actions/runs/11652286864/job/32443297864)

### Additional Context
In the [release.yaml GitHub workflow](https://github.com/defenseunicorns/uds-package-template/blob/da4899b0cb444ffb8dc457203293abd98d9462c7/.github/workflows/release.yaml#L38-L43), there is a build matrix that results in a job being created for an arm64 unicorn build that is not excluded
```yaml
matrix:
  flavor: [upstream, registry1, unicorn]
  architecture: [amd64, arm64]
  exclude:
    - flavor: registry1
      architecture: arm64
```

In the [root zarf.yaml](https://github.com/defenseunicorns/uds-package-template/blob/da4899b0cb444ffb8dc457203293abd98d9462c7/zarf.yaml#L57-L60), there is a specific exclusion for arm64 under the unicorn flavor
```yaml
only:
  flavor: unicorn
  cluster:
    architecture: amd64
```
