### ISSUE TITLE
Set explicit inputs for `commitlint` and `lint` included components in `.gitlab-ci.yml`

### ISSUE THREAD

**Issue by willswire** [uds-packages/template#64]
Instead of

```
include:
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/commitlint@v1.6.0
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/lint@v1.6.0
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/test@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
      flavor: $FLAVOR
      type: $TYPE
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/publish@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
      flavor: $FLAVOR
      target-repo: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
```

we should have

```
include:
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/commitlint@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/lint@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/test@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
      flavor: $FLAVOR
      type: $TYPE
  - component: $CI_SERVER_FQDN/defenseunicorns/uds/uds-common/publish@v1.6.0
    inputs:
      runs-on: gitlab-runner-8c-${ARCH}
      flavor: $FLAVOR
      target-repo: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
```
